name: ManNamedKim
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06400926574133337
title: Meet Kim the Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7194b4'
    - '#006675'
    - '#020000'
    - '#fd9149'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
